apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-worker-codes
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "308"
spec:
  ingressClassName: kong
  tls:
  - secretName: docs-worker-codes
    hosts:
    - docs.worker.codes
  rules:
  - host: docs.worker.codes
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific        
        backend:
          service:
            name: wrkcodes-docs-service
            port:
              number: 80
